-- Tabla para solicitudes de documentos (paz y salvo, y futuros tipos).
-- Ejecutar en el SQL Editor de Supabase ANTES de desplegar el código que la usa.
-- Gestionada desde el panel admin, pestaña "Paz y Salvos / Docs".

create table if not exists document_requests (
    id          bigint generated by default as identity primary key,
    phone       text not null,
    client_name text default 'Cliente',
    doc_type    text not null,            -- 'paz_salvo' (futuro: otros documentos)
    source      text default 'menu',      -- 'menu' (botón del menú) | 'llm' (agente LLM)
    detalle     text default '',
    completed   boolean default false,
    created_at  timestamptz default now(),
    completed_at timestamptz
);

create index if not exists idx_document_requests_completed on document_requests (completed);
create index if not exists idx_document_requests_phone on document_requests (phone);
