-- Referral A/B test for WhatsApp templates:
-- plantilla_referidos_v1 (descuento en tasa) vs plantilla_referidos_v2
-- (aprobacion express).
--
-- Apply this in Supabase before deploying the feature. The bot still keeps the
-- complete transcript in bot_messages; these tables add experiment-specific
-- assignment, event and referral records for reliable reporting.

create table if not exists referral_ab_assignments (
    id              bigint generated by default as identity primary key,
    campaign_id     text not null default 'referidos_ab_2026_06',
    phone           text not null,
    client_name     text default 'Cliente',
    variant_key     text not null,
    variant_label   text not null,
    template_name   text not null,
    send_status     text not null default 'accepted',
    wamid           text,
    sent_at         timestamptz default now(),
    error_message   text,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    unique (campaign_id, phone)
);

create index if not exists idx_referral_ab_assignments_campaign_sent
    on referral_ab_assignments (campaign_id, sent_at desc);

create index if not exists idx_referral_ab_assignments_variant
    on referral_ab_assignments (campaign_id, variant_key);

create table if not exists referral_ab_events (
    id              bigint generated by default as identity primary key,
    campaign_id     text not null default 'referidos_ab_2026_06',
    phone           text not null,
    variant_key     text,
    event_type      text not null,
        -- sent | send_failed | button_click | info_sent | declined |
        -- capture_started | referral_name | referral_phone | free_text
    event_text      text default '',
    metadata        jsonb not null default '{}'::jsonb,
    created_at      timestamptz not null default now()
);

create index if not exists idx_referral_ab_events_campaign_phone_created
    on referral_ab_events (campaign_id, phone, created_at);

create index if not exists idx_referral_ab_events_type
    on referral_ab_events (campaign_id, event_type);

create table if not exists referral_ab_referrals (
    id              bigint generated by default as identity primary key,
    campaign_id     text not null default 'referidos_ab_2026_06',
    referrer_phone  text not null,
    referrer_name   text default 'Cliente',
    variant_key     text,
    referred_name   text,
    referred_phone  text,
    status          text not null default 'awaiting_phone',
        -- awaiting_phone | completed
    source          text not null default 'bot',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create index if not exists idx_referral_ab_referrals_campaign_referrer
    on referral_ab_referrals (campaign_id, referrer_phone, created_at desc);

create index if not exists idx_referral_ab_referrals_status
    on referral_ab_referrals (campaign_id, status);
